require "plugins.colorscheme"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.indentline"
require "plugins.lualine"
require "plugins.telescope"
require "plugins.gitsigins"
require "plugins.toggleterm"
--require "plugins.illuminate"
require "plugins.treesitter"

